arb-dir: lib/l10n/arb
output-dir: lib/l10n/generated
template-arb-file: intl_en.arb
output-localization-file: app_locale.dart
output-class: AppLocale
preferred-supported-locales: ["en"]
synthetic-package: false
nullable-getter: false
format: false
untranslated-messages-file: lib/l10n/untranslated.json