name: files_tools
description: Files Tools provides tools to perform various operations on files (documents and media), which helps everyone in their everyday life.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.5.2+62

environment:
  sdk: '>=2.18.1 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # For state management.
  flutter_riverpod: ^2.1.1

  # For material you.
#  dynamic_color: ^1.5.4
  dynamic_color:
    git:
      url: https://github.com/chaudharydeepanshu/material-dynamic-color-flutter.git
      ref: main

  # For colorscheme generation.
#  flex_seed_scheme: ^1.1.0

  # For storing user preferences, app themeMode.
  shared_preferences: ^2.0.15

  # For firebase packages. After installing new firebase package run ```flutterfire configure```.
  # https://stackoverflow.com/questions/71803062/flutterfire-cli-how-to-switch-between-separate-firebase-consoles
  firebase_core: ^2.3.0

  # For logging errors.
  firebase_crashlytics: ^3.0.6

  # For logging usage and behavior data.
  firebase_analytics: ^10.0.6

  # For splash screen.
  flutter_native_splash: ^2.2.16

  # For custom animations.
  rive: ^0.9.1

  # For loading animations.
  flutter_spinkit: ^5.1.0

  # For picking and saving single or multiple files.
  pick_or_save: ^2.2.4

  # For pdf bitmaps and page count.
  pdf_bitmaps: ^0.3.2
  # flutter_pdfview: ^1.2.5 it accepts URI so look into it in future

  # For pdf manipulations.
  pdf_manipulator: ^0.5.6

  # For draggable gridview.
  reorderable_grid_view: ^2.2.5

  # For working easily with collections like list.
  collection: ^1.17.0

  # For getting device path like temporary directory path.
  path_provider: ^2.0.11

  # For color picking of text in watermarking pdf.
  flex_color_picker: ^3.0.0

  # For image picking.
  image_picker: ^0.8.6

  # For image editing.
  extended_image: ^6.3.2
  image_editor: ^1.3.0

  # For image compression.
  flutter_image_compress: ^1.1.3

  # For opening urls.
  url_launcher: ^6.1.7

  # For device info.
  device_info_plus: ^8.0.0

  # For app info.
  package_info_plus: ^3.0.2

  # Autoplaying carousel.
  carousel_slider: ^4.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/rive/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: LexendDeca
      fonts:
        - asset: fonts/LexendDeca-Black.ttf
        - asset: fonts/LexendDeca-Bold.ttf
        - asset: fonts/LexendDeca-ExtraBold.ttf
        - asset: fonts/LexendDeca-ExtraLight.ttf
        - asset: fonts/LexendDeca-Light.ttf
        - asset: fonts/LexendDeca-Medium.ttf
        - asset: fonts/LexendDeca-Regular.ttf
        - asset: fonts/LexendDeca-SemiBold.ttf
        - asset: fonts/LexendDeca-Thin.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
